@startuml "WeatherAPI"
skinparam ClassAttributeIconSize 0

class CityController {
    - cityService : ICityService

    + CityController(cityService : ICityService)

    + GetCityList() : ActionResult<IEnumerable<City>>

    + GetCityByCityName(cityName : string) : ActionResult<City>

    + AddCity(city : City) : ActionResult<City>

    + UpdateCity(cityName : string, city : City) : ActionResult<City>

    + DeleteCity(cityName : string) : IActionResult
}

interface ICityService <<interface>> {
    + GetAllCity() : List<City>

    + GetCityByCityName(cityName : string) : City

    + AddCity(city : City) : City

    + UpdateCity(cityName : string, city : City) : City

    + DeleteCity(cityName : string) : void

    + CityExists(cityName : string) : bool
}

class CityService {
    - httpClientService : IHttpClient
    - cityContext : CityContext

    + CityService(\n\
        httpClientService : IHttpClientService,\n\
        cityContext : CityContext)
}

class City {
    + CityName : string
    + latitude : double
    + longitude : double
}

class WeatherController {
    - weatherService : IWeatherService
    - cityService : ICityService

    + WeatherController(\n\
        weatherService : IWeatherService,\n\
        cityService : ICityService\n\
    )

    + GetWeatherByLatLon(\n\
        latitude : double, \n\
        longitude : double\n\
    ) : ActionResult<Weather>

    + GetWeatherByCityName(\n\
        cityName : string\n\
    ) : ActionResult<Weather>
}

interface IWeatherService <<interface>> {
    + GetWeatherByLatLon(\n\
        latitude : double, \n\
        longitude : double\n\
    ) : Weather
}

class WeatherService {
    - httpClientService : IHttpClientService

    + WeatherService(\n\
        httpClientService : IHttpClientService)
}

class Weather {
    + Latitude : double
    + Longitude : double
    + StartDate : DateTime
    + EndDate : DateTime
    + WeatherCodes : List<WeatherCode>
}

Enum WeatherCode {
    ClearSky
    Cloudy
    Fog
    RainOrWorse
}

interface IHttpClientService <<interface>> {
    + GetAsync(url : string) : (string, bool)
}

class HttpClientService {
    - httpClient : HttpClient
	
	+ GetAsync(url : string) : (string, bool)
}

CityController o-- ICityService

ICityService <|.. CityService
ICityService ---> City
WeatherController ----> City

WeatherController o-- IWeatherService
WeatherController o-- ICityService

IWeatherService <|.. WeatherService

WeatherController ----> Weather
IWeatherService ---> Weather

Weather o-- WeatherCode

CityService o-- IHttpClientService
WeatherService o-- IHttpClientService

IHttpClientService <|.. HttpClientService

@enduml